### ISSUE TITLE
Create yeoman generator

### ISSUE THREAD

**Issue by jamesmanning** [codeocelot/react-reflux-webpack-starter#2]
There are a few listed already, like https://github.com/ties/generator-react-reflux-webpack but often a yeoman generator can be easier for someone to use when starting out.

**Comment by codeocelot** [comment]
Hi @jamesmanning .  I'm looking into this.  I've never made a yeoman generator and I'm not sure exactly how complex I feel comfortable taking this project.  I think there is a niche for an mvc project.  What configuration options do you feel this project should include if we develop this into a yeoman gen?

**Comment by jamesmanning** [comment]
The existing generator is likely sufficient, then. People can always just clone this repo to use it.
